# Generated by Django 2.2 on 2019-09-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('other', 'Разное'), ('food', 'Еда'), ('it', 'IT-сфера'), ('psycho', 'Психология'), ('bikes', 'Велосипеды')], default='other', max_length=20, verbose_name='Тема'),
        ),
    ]
