# Generated by Django 2.2 on 2019-09-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('new', 'новый'), ('in_progress', 'в прецесе'), ('done', 'завершена')], default='new', max_length=20, verbose_name='Тема'),
        ),
    ]
