# Generated by Django 2.2.4 on 2019-09-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190906_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(max_length=3000, verbose_name='Дата'),
        ),
    ]
