# Generated by Django 2.2.4 on 2019-09-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20190910_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(max_length=3000, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(max_length=3000, verbose_name='Текст'),
        ),
    ]
